### PR TITLE
modify setCurrent

### PR DESCRIPTION
**Pull request by darkmirrors**
force param num to Number

### CODE REVIEW

**Comment by michaelbromley** [comment]
Out of interest, did you have a case where this caused an issue?

**Comment by darkmirrors** [comment]
@michaelbromley 
In that case pageRander is a String . when i click the `.nextBtn`, `pagination.current + 1` turn out to be  `11` not 2

```html
<a class="syyBtn" ng-class="{backBtnClick : pagination.current != 1}" ng-click="setCurrent(pagination.current - 1)">上一页</a>
<a class="nextBtn " ng-class="{nextBtnClick : pagination.current == pagination.last}" ng-click="setCurrent(pagination.current + 1)">下一页</a>
<input type="text" ng-model="pageRander">
<a class="goNext" ng-click="setCurrent(pageRander)">GO</a>
```

**Comment by michaelbromley** [comment]
Thanks, that makes sense.

**Comment by darkmirrors** [comment]
Ok, thanks. btw, can you update to the bower ?

**Comment by michaelbromley** [comment]
Done - v.0.6.1

**Comment by darkmirrors** [comment]
@michaelbromley nice buddy..

**Pull request merged**
