### PR TITLE
Added Plunker

### PR DESCRIPTION
**Pull request by cr1x56**

### CODE REVIEW

**Comment by michaelbromley** [comment]
Hi, thanks for the PR. Looks like you put some work into this! A couple of questions:

1) Is this basically a fix for this issue: https://github.com/michaelbromley/angularUtils/issues/264?
2) Did you run the unit tests? Did they pass?
3) Are any of the current APIs changes by this?

**Comment by cr1x56** [comment]
Hi,
1) Yes it is a fix for issue #2642) No did not run unit tests3) You mentioned you did not want changes to setCurrent but there was no other way to get it done without rewriting a lot of your existing code. There are multiple changes where the set current now looks at ids which are injected into the pages array, that is to identify if it was ellipses before the current page or after. All other areas referencing the raw pages array now needed to look either attribute since for page numbers they are both the same (attributes are id and display). That more or less covers the major changes
Date: Thu, 4 Aug 2016 00:32:44 -0700

**Comment by michaelbromley** [comment]
Ok. I just ran your changes though the unit tests and there are 8 failing tests:

```
PhantomJS 1.9.2 (Windows 8) dirPagination directive pagination controls should show the correct pagination links at start of sequence FAILED
	Expected [ '‹', '1', '2', '3', '4', '5', '6', '7', '8', '...', '›' ] to equal [ '‹', '1', '2', '3', '4', '5', '6', '7', '...', '100', '›' ].
	Error: Expected [ '‹', '1', '2', '3', '4', '5', '6', '7', '8', '...', '›' ] to equal [ '‹', '1', '2', '3', '4', '5', '6', '7', '...', '100', '›' ].
	    at E:/GitHub/angularUtils/src/directives/pagination/dirPagination.spec.js:453
PhantomJS 1.9.2 (Windows 8): Executed 44 of 140 (1 FAILED) (0 secs / 0.883 secs)
PhantomJS 1.9.2 (Windows 8) dirPagination directive pagination controls should show the correct pagination links in middle sequence FAILED
	Expected [ '‹', '...', '47', '48', '49', '50', '51', '52', '53', '...', '›' ] to equal [ '‹', '1', '...', '48', '49', '50', '51', '52', '...', '100', '›' ].
	Error: Expected [ '‹', '...', '47', '48', '49', '50', '51', '52', '53', '...', '›' ] to equal [ '‹', '1', '...', '48', '49', '50', '51', '52', '...', '100', '›' ].
	    at E:/GitHub/angularUtils/src/directives/pagination/dirPagination.spec.js:463
PhantomJS 1.9.2 (Windows 8): Executed 45 of 140 (2 FAILED) (0 secs / 0.904 secs)
PhantomJS 1.9.2 (Windows 8) dirPagination directive pagination controls should show the correct pagination links at end of sequence FAILED
	Expected [ '‹', '...', '93', '94', '95', '96', '97', '98', '99', '100', '›' ] to equal [ '‹', '1', '...', '94', '95', '96', '97', '98', '99', '100', '›' ].
	Error: Expected [ '‹', '...', '93', '94', '95', '96', '97', '98', '99', '100', '›' ] to equal [ '‹', '1', '...', '94', '95', '96', '97', '98', '99', '100', '›' ].
	    at E:/GitHub/angularUtils/src/directives/pagination/dirPagination.spec.js:473
PhantomJS 1.9.2 (Windows 8): Executed 46 of 140 (3 FAILED) (0 secs / 0.924 secs)
PhantomJS 1.9.2 (Windows 8) dirPagination directive pagination controls should show the correct pagination links after item removed from cllection FAILED
	Expected [ '‹', '...', '92', '93', '94', '95', '96', '97', '98', '99', '›' ] to equal [ '‹', '1', '...', '93', '94', '95', '96', '97', '98', '99', '›' ].
	Error: Expected [ '‹', '...', '92', '93', '94', '95', '96', '97', '98', '99', '›' ] to equal [ '‹', '1', '...', '93', '94', '95', '96', '97', '98', '99', '›' ].
	    at E:/GitHub/angularUtils/src/directives/pagination/dirPagination.spec.js:487
PhantomJS 1.9.2 (Windows 8): Executed 47 of 140 (4 FAILED) (0 secs / 0.943 secs)
PhantomJS 1.9.2 (Windows 8): Executed 48 of 140 (4 FAILED) (0 secs / 0.962 secs)
PhantomJS 1.9.2 (Windows 8): Executed 49 of 140 (4 FAILED) (0 secs / 0.984 secs)
PhantomJS 1.9.2 (Windows 8): Executed 50 of 140 (4 FAILED) (0 secs / 1.004 secs)
PhantomJS 1.9.2 (Windows 8) dirPagination directive pagination controls optional attributes should accept a max-size attribute to limit the length of the control FAILED
	Expected [ '‹', '1', '2', '3', '4', '...', '›' ] to equal [ '‹', '1', '2', '3', '...', '10', '›' ].
	Error: Expected [ '‹', '1', '2', '3', '4', '...', '›' ] to equal [ '‹', '1', '2', '3', '...', '10', '›' ].
	    at E:/GitHub/angularUtils/src/directives/pagination/dirPagination.spec.js:557
PhantomJS 1.9.2 (Windows 8): Executed 51 of 140 (5 FAILED) (0 secs / 1.021 secs)
PhantomJS 1.9.2 (Windows 8) dirPagination directive pagination controls optional attributes should alter links array when value of max-size changes FAILED
	Expected [ '‹', '1', '2', '3', '4', '...', '›' ] to equal [ '‹', '1', '2', '3', '...', '10', '›' ].
	Error: Expected [ '‹', '1', '2', '3', '4', '...', '›' ] to equal [ '‹', '1', '2', '3', '...', '10', '›' ].
	    at E:/GitHub/angularUtils/src/directives/pagination/dirPagination.spec.js:566
	Expected [ '‹', '1', '2', '3', '4', '5', '6', '7', '8', '...', '›' ] to equal [ '‹', '1', '2', '3', '4', '5', '6', '7', '...', '10', '›' ].
	Error: Expected [ '‹', '1', '2', '3', '4', '5', '6', '7', '8', '...', '›' ] to equal [ '‹', '1', '2', '3', '4', '5', '6', '7', '...', '10', '›' ].
	    at E:/GitHub/angularUtils/src/directives/pagination/dirPagination.spec.js:574
PhantomJS 1.9.2 (Windows 8): Executed 52 of 140 (6 FAILED) (0 secs / 1.04 secs)
PhantomJS 1.9.2 (Windows 8) dirPagination directive pagination controls optional attributes should impose a minimum max-size of 5 FAILED
	Expected [ '‹', '1', '2', '3', '4', '...', '›' ] to equal [ '‹', '1', '2', '3', '...', '10', '›' ].
	Error: Expected [ '‹', '1', '2', '3', '4', '...', '›' ] to equal [ '‹', '1', '2', '3', '...', '10', '›' ].
	    at E:/GitHub/angularUtils/src/directives/pagination/dirPagination.spec.js:582
PhantomJS 1.9.2 (Windows 8): Executed 53 of 140 (7 FAILED) (0 secs / 1.057 secs)
PhantomJS 1.9.2 (Windows 8) dirPagination directive pagination controls optional attributes should go to the last page when clicking the end arrow FAILED
	Expected 5 to be 10.
	Error: Expected 5 to be 10.
	    at E:/GitHub/angularUtils/src/directives/pagination/dirPagination.spec.js:591
```

I don't have time to try to fix this, but you are welcome to. If you need help getting the tests running, let me know.

**Comment by cr1x56** [comment]
Hi,
I reordered the links so that they made a bit more sense. The current order to me is a bit unnecessary as the final value works exactly as the last button and the same with the 1 at the beginning as you page through. Let me know if this makes sense.
You needed the final button to be the last page for our APIs to work properly so that was changed also to store the last page value in the pages object
PS. I took the ordering out of another pagination function as it seemed more usable to me

Date: Fri, 5 Aug 2016 00:56:49 -0700

**Comment by michaelbromley** [comment]
Ah okay, that's why the tests fail then. I'm going to be able to take a look at this again towards the end of the week.

**Comment by cr1x56** [comment]
@michaelbromley Got time to look into this?

**Comment by cr1x56** [comment]
@michaelbromley is this now dormant?

**Pull request closed without merging**
